import { pool } from "./db";

export async function seedCondominiums() {
  try {
    console.log("[SEED] Starting condominiums seed check...");

    const condominiums = [
      {
        id: "a7af9126-67ff-47d9-9c24-cf4054aeb63c",
        name: "サンプルレジデンス青楓",
        address: "東京都江東区木場1-2-3",
        units: 437,
        build_year: 1985,
        management_start_date: "2020-04-01",
        current_regulation_version: "5.0",
        law_revision_status: "completed",
        assigned_manager: "修繕 未来",
        structure_type: "RC造",
        floors: 12,
        management_type: "全部委託",
        reserve_fund_balance: 9600,
        reserve_fund_monthly: 12000,
        management_fee_monthly: 8500,
        delinquency_rate: "2.5",
        proper_evaluation_score: 72,
        proper_evaluation_star: 3,
        long_term_plan_version: "第2版",
        long_term_plan_date: "2018-10-01",
      },
      {
        id: "b8bf0237-78ee-48ea-ad35-df5165bfb74d",
        name: "ノヴァコート海風",
        address: "神奈川県横浜市港北区2-3-4",
        units: 85,
        build_year: 2006,
        management_start_date: "2018-01-01",
        current_regulation_version: "3.2",
        law_revision_status: "in_progress",
        assigned_manager: "佐藤花子",
        structure_type: null,
        floors: null,
        management_type: null,
        reserve_fund_balance: null,
        reserve_fund_monthly: null,
        management_fee_monthly: null,
        delinquency_rate: null,
        proper_evaluation_score: null,
        proper_evaluation_star: null,
        long_term_plan_version: null,
        long_term_plan_date: null,
      },
      {
        id: "6aa176b1-0fb6-4217-b334-dccebfb03d68",
        name: "リーフテラス橘",
        address: "東京都立川市錦町3-5-10",
        units: 120,
        build_year: 2001,
        management_start_date: "2015-07-01",
        current_regulation_version: "4.1",
        law_revision_status: "completed",
        assigned_manager: "田中一郎",
        structure_type: "RC造",
        floors: 10,
        management_type: "全部委託",
        reserve_fund_balance: 4800,
        reserve_fund_monthly: 10500,
        management_fee_monthly: 9200,
        delinquency_rate: "0.8",
        proper_evaluation_score: 80,
        proper_evaluation_star: 4,
        long_term_plan_version: "第3版",
        long_term_plan_date: "2022-04-01",
      },
      {
        id: "c25d20d2-e3ea-46a7-b866-3ca38d553bf8",
        name: "フォレストゲート澄川",
        address: "神奈川県川崎市川崎区砂子1-8-22",
        units: 56,
        build_year: 1998,
        management_start_date: "2012-04-01",
        current_regulation_version: "2.8",
        law_revision_status: "pending",
        assigned_manager: "山田太郎",
        structure_type: "RC造",
        floors: 6,
        management_type: "一部委託",
        reserve_fund_balance: 1850,
        reserve_fund_monthly: 7500,
        management_fee_monthly: 6200,
        delinquency_rate: "4.1",
        proper_evaluation_score: 52,
        proper_evaluation_star: 2,
        long_term_plan_version: "第1版",
        long_term_plan_date: "2016-09-01",
      },
      {
        id: "86d64213-2915-4433-a906-bb10138e2823",
        name: "グレイスノート若葉",
        address: "埼玉県さいたま市浦和区仲町2-12-5",
        units: 200,
        build_year: 2010,
        management_start_date: "2022-01-01",
        current_regulation_version: "2.0",
        law_revision_status: "in_progress",
        assigned_manager: "鈴木美咲",
        structure_type: "RC造",
        floors: 15,
        management_type: "全部委託",
        reserve_fund_balance: 7200,
        reserve_fund_monthly: 11000,
        management_fee_monthly: 9800,
        delinquency_rate: "1.5",
        proper_evaluation_score: 78,
        proper_evaluation_star: 4,
        long_term_plan_version: "第2版",
        long_term_plan_date: "2023-03-20",
      },
      {
        id: "7bd45ba6-222f-464f-89bd-3b8f8df8dfa2",
        name: "セレスティア千景",
        address: "千葉県千葉市中央区富士見1-4-8",
        units: 148,
        build_year: 2003,
        management_start_date: "2019-10-01",
        current_regulation_version: "3.5",
        law_revision_status: "completed",
        assigned_manager: "伊藤健二",
        structure_type: "SRC造",
        floors: 18,
        management_type: "全部委託",
        reserve_fund_balance: 5500,
        reserve_fund_monthly: 10000,
        management_fee_monthly: 8800,
        delinquency_rate: "2.0",
        proper_evaluation_score: 69,
        proper_evaluation_star: 3,
        long_term_plan_version: "第2版",
        long_term_plan_date: "2020-07-10",
      },
      {
        id: "1af5d112-b4dc-4d7f-8cd8-3e0077cd5e79",
        name: "ブリーズコート光葉",
        address: "東京都町田市原町田4-6-15",
        units: 72,
        build_year: 1994,
        management_start_date: "2010-06-01",
        current_regulation_version: "5.3",
        law_revision_status: "completed",
        assigned_manager: "渡辺裕子",
        structure_type: "RC造",
        floors: 7,
        management_type: "自主管理",
        reserve_fund_balance: 2100,
        reserve_fund_monthly: 6800,
        management_fee_monthly: 5500,
        delinquency_rate: "5.2",
        proper_evaluation_score: 45,
        proper_evaluation_star: 2,
        long_term_plan_version: "第4版",
        long_term_plan_date: "2019-01-15",
      },
      {
        id: "cff09745-0233-4b13-b747-c29ed0d69e54",
        name: "ベルクレスト新緑",
        address: "千葉県松戸市新松戸3-7-2",
        units: 96,
        build_year: 2008,
        management_start_date: "2021-04-01",
        current_regulation_version: "1.5",
        law_revision_status: "in_progress",
        assigned_manager: "中村雄一",
        structure_type: "RC造",
        floors: 9,
        management_type: "全部委託",
        reserve_fund_balance: 3600,
        reserve_fund_monthly: 9500,
        management_fee_monthly: 8200,
        delinquency_rate: "1.8",
        proper_evaluation_score: 61,
        proper_evaluation_star: 3,
        long_term_plan_version: "第1版",
        long_term_plan_date: "2021-09-30",
      },
      {
        id: "09d873ad-3061-438a-8093-278f0df1cbbf",
        name: "アクアノート汐風",
        address: "神奈川県藤沢市片瀬海岸1-10-3",
        units: 65,
        build_year: 2015,
        management_start_date: "2023-07-01",
        current_regulation_version: "1.0",
        law_revision_status: "pending",
        assigned_manager: "小林さくら",
        structure_type: "RC造",
        floors: 11,
        management_type: "全部委託",
        reserve_fund_balance: 2800,
        reserve_fund_monthly: 13000,
        management_fee_monthly: 11500,
        delinquency_rate: "0.5",
        proper_evaluation_score: 85,
        proper_evaluation_star: 4,
        long_term_plan_version: "第1版",
        long_term_plan_date: "2023-07-01",
      },
      {
        id: "55b3d6d2-6b27-4f6a-8a10-b55c7b07306b",
        name: "ウィンドアーク桜",
        address: "埼玉県さいたま市大宮区桜木町1-15-9",
        units: 310,
        build_year: 1990,
        management_start_date: "2008-01-01",
        current_regulation_version: "6.0",
        law_revision_status: "completed",
        assigned_manager: "加藤誠司",
        structure_type: "SRC造",
        floors: 20,
        management_type: "全部委託",
        reserve_fund_balance: 12400,
        reserve_fund_monthly: 13500,
        management_fee_monthly: 10200,
        delinquency_rate: "3.0",
        proper_evaluation_score: 74,
        proper_evaluation_star: 3,
        long_term_plan_version: "第5版",
        long_term_plan_date: "2024-02-28",
      },
      {
        id: "d1e2f3a4-b5c6-7890-abcd-ef1234567890",
        name: "スカイリーフ碧",
        address: "東京都品川区大崎2-1-5",
        units: 180,
        build_year: 2005,
        management_start_date: "2017-04-01",
        current_regulation_version: "4.0",
        law_revision_status: "completed",
        assigned_manager: "松本健太",
        structure_type: "RC造",
        floors: 14,
        management_type: "全部委託",
        reserve_fund_balance: 6800,
        reserve_fund_monthly: 11500,
        management_fee_monthly: 9600,
        delinquency_rate: "1.2",
        proper_evaluation_score: 82,
        proper_evaluation_star: 4,
        long_term_plan_version: "第3版",
        long_term_plan_date: "2022-10-01",
      },
      {
        id: "e2f3a4b5-c6d7-8901-bcde-f12345678901",
        name: "プラムテラス翠",
        address: "東京都世田谷区三軒茶屋1-8-12",
        units: 95,
        build_year: 2012,
        management_start_date: "2020-10-01",
        current_regulation_version: "2.5",
        law_revision_status: "in_progress",
        assigned_manager: "高橋奈々",
        structure_type: "RC造",
        floors: 8,
        management_type: "全部委託",
        reserve_fund_balance: 3900,
        reserve_fund_monthly: 12000,
        management_fee_monthly: 10500,
        delinquency_rate: "0.9",
        proper_evaluation_score: 77,
        proper_evaluation_star: 4,
        long_term_plan_version: "第2版",
        long_term_plan_date: "2023-06-15",
      },
      {
        id: "f3a4b5c6-d7e8-9012-cdef-012345678902",
        name: "ソレイユノヴァ南",
        address: "埼玉県越谷市南越谷4-12-8",
        units: 130,
        build_year: 1999,
        management_start_date: "2014-07-01",
        current_regulation_version: "3.8",
        law_revision_status: "pending",
        assigned_manager: "木村浩二",
        structure_type: "RC造",
        floors: 11,
        management_type: "一部委託",
        reserve_fund_balance: 4200,
        reserve_fund_monthly: 8500,
        management_fee_monthly: 7200,
        delinquency_rate: "3.5",
        proper_evaluation_score: 58,
        proper_evaluation_star: 2,
        long_term_plan_version: "第2版",
        long_term_plan_date: "2017-03-20",
      },
      {
        id: "a4b5c6d7-e8f9-0123-defa-123456789003",
        name: "コンフォートリーフ千景",
        address: "東京都足立区千住2-5-7",
        units: 68,
        build_year: 1996,
        management_start_date: "2011-01-01",
        current_regulation_version: "4.5",
        law_revision_status: "completed",
        assigned_manager: "吉田真由美",
        structure_type: "RC造",
        floors: 7,
        management_type: "自主管理",
        reserve_fund_balance: 1650,
        reserve_fund_monthly: 7000,
        management_fee_monthly: 5800,
        delinquency_rate: "6.1",
        proper_evaluation_score: 43,
        proper_evaluation_star: 2,
        long_term_plan_version: "第3版",
        long_term_plan_date: "2020-04-01",
      },
      {
        id: "b5c6d7e8-f9a0-1234-efab-234567890004",
        name: "グランフォレスト東雲",
        address: "神奈川県川崎市中原区新丸子東3-4-6",
        units: 245,
        build_year: 2014,
        management_start_date: "2021-07-01",
        current_regulation_version: "1.8",
        law_revision_status: "in_progress",
        assigned_manager: "中島拓也",
        structure_type: "SRC造",
        floors: 22,
        management_type: "全部委託",
        reserve_fund_balance: 9800,
        reserve_fund_monthly: 14000,
        management_fee_monthly: 12000,
        delinquency_rate: "0.6",
        proper_evaluation_score: 88,
        proper_evaluation_star: 5,
        long_term_plan_version: "第1版",
        long_term_plan_date: "2021-07-01",
      },
      {
        id: "c6d7e8f9-a0b1-2345-fabc-345678900005",
        name: "レジデンスノヴァ柏葉",
        address: "千葉県柏市柏3-8-15",
        units: 110,
        build_year: 2002,
        management_start_date: "2016-04-01",
        current_regulation_version: "3.2",
        law_revision_status: "completed",
        assigned_manager: "西村恵子",
        structure_type: "RC造",
        floors: 10,
        management_type: "全部委託",
        reserve_fund_balance: 4500,
        reserve_fund_monthly: 9800,
        management_fee_monthly: 8400,
        delinquency_rate: "2.2",
        proper_evaluation_score: 65,
        proper_evaluation_star: 3,
        long_term_plan_version: "第2版",
        long_term_plan_date: "2019-09-30",
      },
      {
        id: "d7e8f9a0-b1c2-3456-abcd-456789000006",
        name: "ビラセレーノ川景",
        address: "埼玉県川口市幸町3-1-9",
        units: 78,
        build_year: 2007,
        management_start_date: "2018-10-01",
        current_regulation_version: "2.1",
        law_revision_status: "pending",
        assigned_manager: "岡田誠一",
        structure_type: "RC造",
        floors: 8,
        management_type: "一部委託",
        reserve_fund_balance: 2950,
        reserve_fund_monthly: 8800,
        management_fee_monthly: 7600,
        delinquency_rate: "2.8",
        proper_evaluation_score: 60,
        proper_evaluation_star: 3,
        long_term_plan_version: "第1版",
        long_term_plan_date: "2022-01-15",
      },
      {
        id: "e8f9a0b1-c2d3-4567-bcde-567890000007",
        name: "ミッドオーブ港星",
        address: "神奈川県横浜市西区みなとみらい4-6-2",
        units: 320,
        build_year: 2018,
        management_start_date: "2024-01-01",
        current_regulation_version: "1.0",
        law_revision_status: "pending",
        assigned_manager: "佐々木彩",
        structure_type: "SRC造",
        floors: 28,
        management_type: "全部委託",
        reserve_fund_balance: 11200,
        reserve_fund_monthly: 15000,
        management_fee_monthly: 13500,
        delinquency_rate: "0.3",
        proper_evaluation_score: 90,
        proper_evaluation_star: 5,
        long_term_plan_version: "第1版",
        long_term_plan_date: "2024-01-01",
      },
      {
        id: "f9a0b1c2-d3e4-5678-cdef-678900000008",
        name: "アーバンリーフ市景",
        address: "千葉県市川市南八幡2-10-3",
        units: 88,
        build_year: 2000,
        management_start_date: "2013-04-01",
        current_regulation_version: "4.2",
        law_revision_status: "completed",
        assigned_manager: "前田幸雄",
        structure_type: "RC造",
        floors: 9,
        management_type: "全部委託",
        reserve_fund_balance: 3200,
        reserve_fund_monthly: 9200,
        management_fee_monthly: 7900,
        delinquency_rate: "1.9",
        proper_evaluation_score: 70,
        proper_evaluation_star: 3,
        long_term_plan_version: "第3版",
        long_term_plan_date: "2021-03-31",
      },
      {
        id: "a0b1c2d3-e4f5-6789-defa-789000000009",
        name: "フォレストノート八葉",
        address: "東京都八王子市元本郷町2-3-8",
        units: 52,
        build_year: 1993,
        management_start_date: "2009-04-01",
        current_regulation_version: "5.1",
        law_revision_status: "completed",
        assigned_manager: "藤田幸子",
        structure_type: "RC造",
        floors: 6,
        management_type: "自主管理",
        reserve_fund_balance: 1480,
        reserve_fund_monthly: 6500,
        management_fee_monthly: 5200,
        delinquency_rate: "4.8",
        proper_evaluation_score: 48,
        proper_evaluation_star: 2,
        long_term_plan_version: "第4版",
        long_term_plan_date: "2018-07-01",
      },
    ];

    console.log("[SEED] Upserting condominiums data...");

    for (const c of condominiums) {
      await pool.query(
        `INSERT INTO condominiums
           (id, name, address, units, build_year, management_start_date,
            current_regulation_version, law_revision_status, assigned_manager,
            structure_type, floors, management_type, reserve_fund_balance,
            reserve_fund_monthly, management_fee_monthly, delinquency_rate,
            proper_evaluation_score, proper_evaluation_star,
            long_term_plan_version, long_term_plan_date, created_at)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,NOW())
         ON CONFLICT (id) DO NOTHING`,
        [
          c.id, c.name, c.address, c.units, c.build_year,
          c.management_start_date, c.current_regulation_version,
          c.law_revision_status, c.assigned_manager,
          c.structure_type, c.floors, c.management_type, c.reserve_fund_balance,
          c.reserve_fund_monthly, c.management_fee_monthly, c.delinquency_rate,
          c.proper_evaluation_score, c.proper_evaluation_star,
          c.long_term_plan_version, c.long_term_plan_date,
        ]
      );
    }

    console.log(`[SEED] Successfully upserted ${condominiums.length} condominiums.`);
  } catch (error) {
    console.error("[SEED] Error seeding condominiums:", error);
    throw error;
  }
}
